[package]
name = "mdbook-trpl-note"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
mdbook = { version = "0.4", default-features = false }     # only need the library
pulldown-cmark = { version = "0.11", features = ["simd"] }
pulldown-cmark-to-cmark = "15"
serde_json = "1"

[dev-dependencies]
assert_cmd = "2"
